game.AddParticles( "particles/bo1/raygun.pcf" )
--game.AddParticles( "particles/bo1/bo1_muzzleflashes.pcf" )
game.AddParticles( "particles/bo1/bo1_pap_muzzle.pcf" )

--PrecacheParticleSystem("pap_muzzleflash")
PrecacheParticleSystem("pap_muzzle")
PrecacheParticleSystem("pap_flamering")
PrecacheParticleSystem("pap_heavy_flame")
PrecacheParticleSystem("pap_muzzle_big")
PrecacheParticleSystem("pap_muzzle_sparks")
PrecacheParticleSystem("pap_trail")

PrecacheParticleSystem("raygun_splash")
PrecacheParticleSystem("raygun_splash_parts")
PrecacheParticleSystem("raygun_splash_pap")
PrecacheParticleSystem("raygun_splash_pap_parts")
PrecacheParticleSystem("raygun_trail")
PrecacheParticleSystem("raygun_trail_pap")
PrecacheParticleSystem("raygun_flash")
PrecacheParticleSystem("raygun_flash_pap")